/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'

const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/orders': typeof OrdersRouteWithChildren
  '/portal': typeof PortalRoute
  '/settings': typeof SettingsRoute
  '/tracking': typeof TrackingRoute
  '/vendors': typeof VendorsRoute
  '/orders/$id': typeof OrdersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/orders': typeof OrdersRouteWithChildren
  '/portal': typeof PortalRoute
  '/settings': typeof SettingsRoute
  '/tracking': typeof TrackingRoute
  '/vendors': typeof VendorsRoute
  '/orders/$id': typeof OrdersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/orders': typeof OrdersRouteWithChildren
  '/portal': typeof PortalRoute
  '/settings': typeof SettingsRoute
  '/tracking': typeof TrackingRoute
  '/vendors': typeof VendorsRoute
  '/orders/$id': typeof OrdersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/orders'
    | '/portal'
    | '/settings'
    | '/tracking'
    | '/vendors'
    | '/orders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/orders'
    | '/portal'
    | '/settings'
    | '/tracking'
    | '/vendors'
    | '/orders/$id'
  id:
    | '__root__'
    | '/'
    | '/orders'
    | '/portal'
    | '/settings'
    | '/tracking'
    | '/vendors'
    | '/orders/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PortalRoute: typeof PortalRoute
  SettingsRoute: typeof SettingsRoute
  TrackingRoute: typeof TrackingRoute
  VendorsRoute: typeof VendorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof OrdersRoute
    }
  }
}

interface OrdersRouteChildren {
  OrdersIdRoute: typeof OrdersIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersIdRoute: OrdersIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PortalRoute: PortalRoute,
  SettingsRoute: SettingsRoute,
  TrackingRoute: TrackingRoute,
  VendorsRoute: VendorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
